version: "3.8"
services:
  po-processor:
    build: .
    container_name: po-processor
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/nas_folder_monitor.py') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - /volume1/Main/Main/ParkerPOsOCR/Scans:/app/input
      - /volume1/Main/Main/ParkerPOsOCR/POs:/app/processed
      - /volume1/Main/Main/ParkerPOsOCR/Archive:/app/archive
      - /volume1/Main/Main/ParkerPOsOCR/Errors:/app/errors
      - ./logs:/app/logs
    environment:
      - TZ=America/Los_Angeles
      - PYTHONUNBUFFERED=1
      - FILEMAKER_ENABLED=true
      - FILEMAKER_SERVER=https://192.168.0.105:443
      - FILEMAKER_DATABASE=PreInventory
      - FILEMAKER_LAYOUT=PreInventory
      - FILEMAKER_SCRIPT=PDFTimesheet
      - FILEMAKER_PRINT_LAYOUT=Time Clock Reduced
      - FILEMAKER_USERNAME=JSON
      - FILEMAKER_PASSWORD=Windu63Purple!
      - DASHBOARD_URLS=https://192.168.0.62:9443/api/notifications/send,https://127.0.0.1:9443/api/notifications/send
      - DASHBOARD_AUTH_USER=anthony
      - DASHBOARD_AUTH_PASS=password

  po-dashboard:
    build: ../dashboard
    container_name: po-dashboard
    network_mode: host
    restart: unless-stopped
    volumes:
      - /volume1/Main/Main/ParkerPOsOCR/dashboard/logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Los_Angeles
      - PYTHONUNBUFFERED=1
      - FILEMAKER_ENABLED=true
      - FILEMAKER_SERVER=https://192.168.0.105:443
      - FILEMAKER_DATABASE=PreInventory
      - FILEMAKER_LAYOUT=PreInventory
      - FILEMAKER_SCRIPT=PDFTimesheet
      - FILEMAKER_PRINT_LAYOUT=Time Clock Reduced
      - FILEMAKER_USERNAME=JSON
      - FILEMAKER_PASSWORD=Windu63Purple!